<div class="container">

    <div class="row">
        <a href="https://github.com/faelp22/DownProxy/blob/master/LICENSE"><img class="pull-right" src="http://www.gnu.org/graphics/gplv3-88x31.png"></a>
        <h2><a href="<?php echo $index; ?>"><?php echo $msgTitle; ?></a></h2>
        <h4><span id="msg"></span><span id="tempo"></span>:<span id="tempo2"></span>!</h4>
        <hr>
        <?php require_once \PROJECT_PATH . '/view/forms/formIndex.phtml'; ?>
        <hr>
    </div>
    <div class="row">
        <img class="pull-right" src="<?php echo \PROJECT_INDEX; ?>view/img/loading.gif" width="20">
        <img class="pull-right" src="<?php echo \PROJECT_INDEX; ?>view/img/loading.gif" width="20">
        <table class="table table-bordered table-condensed">
            <thead>
                <tr>
                    <th>#</th>
                    <th>File Name</th>
                    <th>Date</th>
                    <th>Size</th>
                </tr>
            </thead>
            <tbody>
                <?php get_content(); ?>
            </tbody>
        </table>
        <hr>
    </div>
